# Generated by Django 6.1.1 on 2026-10-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_db',
            fields=[
                ('Vehicle_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Owner_name', models.CharField(max_length=40)),
                ('Insurance_no', models.IntegerField()),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
                ('Service_no', models.IntegerField()),
            ],
        ),
    ]
